FROM golang:1.13.1-stretch as builder
ADD . $GOPATH/src/dagger
WORKDIR $GOPATH/src/dagger
ENV GO111MODULE="on"
ENV GOPROXY="https://goproxy.cn"
RUN go mod download && CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -o dagger backend/main.go

FROM ubuntu:18.04 as backend
WORKDIR /usr/src/app
COPY --from=builder /go/src/dagger/dagger .
COPY backend/dagger.ini /etc/dagger/dagger.ini
LABEL MAINTAINER="leon.chen"

RUN apt-get update

CMD ["sh", "-c", "./dagger"]
