FROM node:14.13 as builder
WORKDIR /usr/src/app
COPY ui .
RUN npm i npm@latest -g && npm install && npm run build

FROM nginx:alpine as ui
WORKDIR /usr/src/app
COPY ./ui/ng-dagger.conf /etc/nginx/conf.d/ng-dagger.conf
COPY --from=builder /usr/src/app/dist dist
LABEL MAINTAINER="leon.chen"

CMD ["nginx", "-g", "daemon off;"]
